import type { PageData } from "./schemas"

export const TEMPLATES: Record<string, PageData> = {
  "luxury-villas": {
    id: "luxury-villas-1",
    name: "Luxury Villas",
    theme: "light",
    templateId: "luxury-villas",
    updatedAt: new Date().toISOString(),
    seo: {
      title: "Luxury Villas - Premium Properties",
      description: "Discover our collection of luxury villas",
    },
    sections: [
      {
        id: "hero-1",
        type: "hero",
        heading: "Discover Luxury Living",
        subheading: "Explore our exclusive collection of premium villas",
        ctaLabel: "View Properties",
        ctaHref: "#listings",
        bgType: "image",
        bgSrc: "/luxury-villa-exterior.png",
        overlayOpacity: 0.3,
      },
      {
        id: "listings-1",
        type: "listings",
        title: "Featured Properties",
        layout: "grid",
        properties: [
          {
            id: "1",
            title: "Modern Villa with Pool",
            description: "Stunning modern villa with infinity pool and ocean views",
            price: 2500000,
            location: "Malibu, California",
            bedrooms: 5,
            bathrooms: 4,
            areaSqFt: 8500,
            images: ["/modern-villa.png"],
            features: ["Pool", "Ocean View", "Smart Home", "Garage"],
            status: "for-sale",
            contactEmail: "info@luxuryvillas.com",
          },
          {
            id: "2",
            title: "Mediterranean Estate",
            description: "Elegant Mediterranean villa with lush gardens",
            price: 3200000,
            location: "Côte d'Azur, France",
            bedrooms: 6,
            bathrooms: 5,
            areaSqFt: 9200,
            images: ["/mediterranean-villa.png"],
            features: ["Wine Cellar", "Tennis Court", "Spa", "Helipad"],
            status: "for-sale",
            contactEmail: "info@luxuryvillas.com",
          },
          {
            id: "3",
            title: "Contemporary Masterpiece",
            description: "Award-winning architectural design with premium finishes",
            price: 4100000,
            location: "Beverly Hills, California",
            bedrooms: 7,
            bathrooms: 6,
            areaSqFt: 10500,
            images: ["/contemporary-villa.jpg"],
            features: ["Home Theater", "Gym", "Sauna", "Smart Automation"],
            status: "for-sale",
            contactEmail: "info@luxuryvillas.com",
          },
        ],
      },
      {
        id: "about-1",
        type: "about",
        title: "About Our Collection",
        content:
          "We specialize in curating the finest luxury properties worldwide. Each villa is handpicked for its architectural excellence, location, and investment potential.",
        image: "/luxury-real-estate-office.jpg",
      },
      {
        id: "testimonials-1",
        type: "testimonials",
        title: "Client Testimonials",
        items: [
          {
            id: "1",
            name: "James Mitchell",
            role: "Property Owner",
            content: "Exceptional service and attention to detail. Found my dream villa!",
            image: "/professional-headshot.png",
          },
          {
            id: "2",
            name: "Sarah Johnson",
            role: "Investor",
            content: "Outstanding portfolio of properties. Highly recommended!",
            image: "/professional-headshot.png",
          },
        ],
      },
      {
        id: "portal-1",
        type: "portal",
        title: "Get in Touch",
        subtitle: "Contact us to schedule a viewing or inquire about properties",
      },
    ],
  },
  "commercial-properties": {
    id: "commercial-1",
    name: "Commercial Properties",
    theme: "light",
    templateId: "commercial-properties",
    updatedAt: new Date().toISOString(),
    seo: {
      title: "Commercial Properties - Office & Retail Spaces",
      description: "Premium commercial real estate solutions",
    },
    sections: [
      {
        id: "hero-2",
        type: "hero",
        heading: "Premium Commercial Spaces",
        subheading: "Office, retail, and warehouse solutions for your business",
        ctaLabel: "Explore Listings",
        ctaHref: "#listings",
        bgType: "image",
        bgSrc: "/modern-office-building.png",
        overlayOpacity: 0.4,
      },
      {
        id: "listings-2",
        type: "listings",
        title: "Available Properties",
        layout: "grid",
        properties: [
          {
            id: "4",
            title: "Downtown Office Tower",
            description: "Class A office space in prime downtown location",
            price: 5000000,
            location: "New York, NY",
            bedrooms: 0,
            bathrooms: 0,
            areaSqFt: 50000,
            images: ["/office-tower.jpg"],
            features: ["24/7 Security", "Parking", "Conference Rooms", "High-Speed Internet"],
            status: "for-rent",
            contactEmail: "commercial@realestate.com",
          },
          {
            id: "5",
            title: "Retail Shopping Center",
            description: "High-traffic retail space with excellent visibility",
            price: 2800000,
            location: "Los Angeles, CA",
            bedrooms: 0,
            bathrooms: 0,
            areaSqFt: 35000,
            images: ["/bustling-shopping-center.png"],
            features: ["Ample Parking", "Loading Dock", "Flexible Layout", "Signage"],
            status: "for-rent",
            contactEmail: "commercial@realestate.com",
          },
        ],
      },
      {
        id: "faq-1",
        type: "faq",
        title: "Frequently Asked Questions",
        items: [
          {
            id: "1",
            question: "What lease terms are available?",
            answer: "We offer flexible lease terms ranging from 1 to 10 years depending on the property.",
          },
          {
            id: "2",
            question: "Are utilities included?",
            answer: "Utilities vary by property. Please contact us for specific details.",
          },
        ],
      },
      {
        id: "portal-2",
        type: "portal",
        title: "Schedule a Tour",
        subtitle: "Contact our commercial team to arrange a property viewing",
      },
    ],
  },
  "housing-society": {
    id: "housing-society-1",
    name: "Housing Society",
    theme: "light",
    templateId: "housing-society",
    updatedAt: new Date().toISOString(),
    seo: {
      title: "Housing Society - Community Living",
      description: "Discover our vibrant housing community",
    },
    sections: [
      {
        id: "hero-3",
        type: "hero",
        heading: "Welcome to Our Community",
        subheading: "A place where families thrive and dreams come true",
        ctaLabel: "Explore Homes",
        ctaHref: "#listings",
        bgType: "image",
        bgSrc: "/residential-community.jpg",
        overlayOpacity: 0.35,
      },
      {
        id: "about-2",
        type: "about",
        title: "About Our Community",
        content:
          "Our housing society offers a perfect blend of modern living and community values. With world-class amenities and a vibrant neighborhood, we create the ideal environment for families.",
        image: "/community-park.jpg",
      },
      {
        id: "listings-3",
        type: "listings",
        title: "Available Homes",
        layout: "grid",
        properties: [
          {
            id: "6",
            title: "3-Bedroom Family Home",
            description: "Spacious family home with modern amenities",
            price: 450000,
            location: "Housing Society, District 1",
            bedrooms: 3,
            bathrooms: 2,
            areaSqFt: 2500,
            images: ["/cozy-family-home.png"],
            features: ["Garden", "Garage", "Modern Kitchen", "Balcony"],
            status: "for-sale",
            contactEmail: "sales@housingsociety.com",
          },
          {
            id: "7",
            title: "4-Bedroom Villa",
            description: "Premium villa with exclusive amenities",
            price: 650000,
            location: "Housing Society, District 2",
            bedrooms: 4,
            bathrooms: 3,
            areaSqFt: 3500,
            images: ["/villa-home.jpg"],
            features: ["Swimming Pool", "Landscaped Garden", "Home Office", "Terrace"],
            status: "for-sale",
            contactEmail: "sales@housingsociety.com",
          },
        ],
      },
      {
        id: "faq-2",
        type: "faq",
        title: "Community FAQs",
        items: [
          {
            id: "1",
            question: "What amenities are available?",
            answer: "We offer parks, swimming pools, sports courts, community center, and 24/7 security.",
          },
          {
            id: "2",
            question: "Are there financing options?",
            answer: "Yes, we work with major banks to provide flexible financing options.",
          },
        ],
      },
      {
        id: "testimonials-2",
        type: "testimonials",
        title: "Happy Residents",
        items: [
          {
            id: "1",
            name: "Ahmed Hassan",
            role: "Resident",
            content: "Best decision we made for our family. Great community!",
            image: "/professional-headshot.png",
          },
          {
            id: "2",
            name: "Fatima Khan",
            role: "Resident",
            content: "Safe, secure, and wonderful neighbors. Highly satisfied!",
            image: "/professional-headshot.png",
          },
        ],
      },
      {
        id: "portal-3",
        type: "portal",
        title: "Join Our Community",
        subtitle: "Contact us to learn more about available properties",
      },
    ],
  },
}
